{% set name = "extcolors" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/extcolors-{{ version }}.tar.gz
  sha256: 14e81457f98555ba36c07a5dde677d1d555e8f4b75633a4fad42df30a27c4f27

build:
  entry_points:
    - extcolors=extcolors.command:main
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 2

requirements:
  host:
    - python {{ python_min }}
    - pip
  run:
    - python >={{ python_min }}
    - pillow >=8.0.0
    - convcolors >=1.0.0

test:
  imports:
    - extcolors
  commands:
    - pip check
    - extcolors --help
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/CairX/extract-colors-py
  summary: Extract colors from an image. Colors are grouped based on visual similarities using the CIE76 formula.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - carlodri
